spring:
  datasource:
    url: jdbc:oracle:thin:@sgrurds.cuilq25exy6o.us-east-1.rds.amazonaws.com:1521/SGRUDB
    username: sgru
    password: Rubricas1
    driver-class-name: oracle.jdbc.OracleDriver